e_learning/course/urls.py
from django.urls import path
from course import views
from django.contrib.auth import views as v

urlpatterns = [
    path('',views.visit,name="visit"),
    path('s_signup',views.s_signup,name="s_signup"),
    path('a_signup',views.a_signup,name="a_signup"),
    path('login',views.login_view,name='login'),
    path('admin_',views.admin_home,name='admin_home'),
    path('a_',views.a_home,name="a_home"),
    path('s_',views.s_home,name="s_home"),
    path('p/<int:id>',views.play,name="play"), #playing the course
	path('add',views.add,name="add"), #adding the course
	# path('a_course',views.a_course,name="a_course"), #View the list of courses of that particular author
    path('s_enroll/<int:vid>',views.s_enroll,name="s_enroll"),# Enroll the student for the course
    path('s_learning',views.s_learning,name="s_learning"), # View the list of enrolled courses of that particular student
    path('logout/',v.LogoutView.as_view(template_name='logout.html'),name='logout'),
    path('a_t_s',views.admin_teacher_status,name="admin_teacher_status"),
    path('a_c_s',views.admin_course_status,name="admin_course_status"),
    path('a_accept_t_s/<int:aid>',views.accept_teacher_status,name="accept_teacher_status"),
    path('a_reject_t_s/<int:aid>',views.reject_teacher_status,name="reject_teacher_status"),
    path('a_submit_v_p/<int:aid>',views.submit_valid_proof,name="submit_valid_proof"),
    path('a_accept_v_s/<int:vid>',views.accept_course_status,name="accept_course_status"),
    path('a_reject_v_s/<int:vid>',views.reject_course_status,name="reject_course_status"),
    path('a_rejected_v/<int:vid>',views.video_rejected,name="video_rejected"),
    path('a_remove_v/<int:vid>',views.remove_video,name="remove"),
    
    
]

e_learning/e_learning/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
]

if settings.DEBUG:
	urlpatterns +=  static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_learning/course/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
	first_name=models.CharField(max_length=30)
	last_name=models.CharField(max_length=30)
	email=models.EmailField(max_length=254,unique = True,error_messages ={
					"unique":"The email you entered is already used. Please Enter another email"
					})
	password=models.CharField(max_length=20)
	username=models.CharField(max_length=30,unique = True,error_messages ={
					"unique":"The username you entered is not unique."
					})
	# a_qualification=models.CharField(max_length=50) It can be accessed using POST object no need to create field for it
	# t=[('Student','Student'),('Student','Author')]
	role=models.CharField(default='Student',max_length=20)

	def __str__(self):
		return self.username

	def uid(self):
		return self.id

class Student(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
	s_name=models.CharField(max_length=30)
	email=models.EmailField(max_length=254)
	def __str__(self):
		return self.s_name
	

class Author(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
	a_name=models.CharField(max_length=30)
	a_qualification=models.CharField(max_length=50)
	email=models.EmailField(max_length=254)
	proof=models.ImageField(upload_to="author_proof",default='1.jpg')
	status=models.CharField(max_length=30,default="Pending")
	
	
	
	def __str__(self):
		return self.a_name

class Video(models.Model):
	title=models.CharField(max_length=36,help_text = "Title should not exceed 36 characters")
	banner=models.ImageField(upload_to="images/",default='1.jpg')
	video=models.FileField(upload_to="video/")
	author=models.ForeignKey(Author,on_delete=models.CASCADE)
	enrolled_student = models.ManyToManyField(Student,blank=True, null=True)
	status=models.CharField(max_length=30,default="Pending")

	def __str__(self):
		return self.title

e_learning/course/forms.py
from django import forms

from .models import Video,Author

from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm

import django.forms.widgets

from django.contrib.auth import get_user_model
User = get_user_model()

class videoform(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title','banner','video']
        widgets={
			
			'title':forms.TextInput(attrs={
				'class':"form-control mt-3",
				'placeholder':"Enter Course Title",
				}),
			'video':forms.FileInput(attrs={
				'class':"mb-3",
				}),

		}

class studentform(UserCreationForm):
	first_name=forms.CharField(label="First name",required=True,widget=forms.TextInput(attrs={'class':"form-control my-3 ",'placeholder':"Enter your first name",}))
	last_name=forms.CharField(label="Last name",required=True,widget=forms.TextInput(attrs={'class':"form-control my-3 ",'placeholder':"Enter your last name",}))
	def __init__(self, *args, **kwargs):		
		super(studentform, self).__init__(*args, **kwargs)
		for fieldname in ['username', 'password1', 'password2']:
			self.fields[fieldname].help_text = None
		self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control my-3'})
		self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control my-3'})
	class Meta:
		fields=("first_name",'last_name','username','email')
		model = User
		widgets={
			
			'username':forms.TextInput(attrs={
				'class':"form-control mt-3",
				'placeholder':"Enter your username",
				}),
			'email':forms.EmailInput(attrs={
				'class':" form-control my-3",
				'placeholder':"Enter your Email"
				}),

		}

class authorform(UserCreationForm):
	first_name=forms.CharField(label="First name",required=True,widget=forms.TextInput(attrs={'class':"form-control my-3 ",'placeholder':"Enter your first name",}))
	last_name=forms.CharField(label="Last name",required=True,widget=forms.TextInput(attrs={'class':"form-control my-3 ",'placeholder':"Enter your last name",}))
	a_qualification=forms.CharField(label="Your Qualification",required=True,widget=forms.TextInput(attrs={'class':"form-control my-3",'placeholder':"Enter your qualifications",}))
	proof=forms.ImageField()
	def __init__(self, *args, **kwargs):		
		super(authorform, self).__init__(*args, **kwargs)
		for fieldname in ['username', 'password1', 'password2']:
			self.fields[fieldname].help_text = None
		self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control my-3'})
		self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control my-3 '})
	class Meta:
		fields=("first_name",'last_name','username','email','a_qualification','proof')
		model = User
		widgets={
			
			'username':forms.TextInput(attrs={
				'class':"form-control my-3",
				'placeholder':"Enter your username",
				}),
			'email':forms.EmailInput(attrs={
				'class':" form-control my-3",
				'placeholder':"Enter your Email"
				}),

		}
	
class Submit_valid_proofs(forms.ModelForm):
	class Meta:
		model=Author
		fields=['proof']
		widgets={

		'proof':forms.FileInput(

			attrs={'required': True}

		)

		}

# class Meta:
# 	model = Author
# 	fields = ['a_name','a_qualification','username','password']
    

# class Registrationform(UserCreationForm):
# 	first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
# 	last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
# 	email=forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}),max_length=100)

# 	def __init__(self, *args, **kwargs):		
# 		super(Registrationform, self).__init__(*args, **kwargs)
# 		for fieldname in ['username', 'password1', 'password2']:
# 			self.fields[fieldname].help_text = None
# 		self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
# 		self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
# 	class Meta:
# 		model=User
# 		fields=("first_name",'last_name','username','email')
# 		widgets={
			
# 			'username':forms.TextInput(attrs={
# 				'class':"form-control"
# 				}),
# 			'password1':forms.PasswordInput(attrs={
# 				'class':"form-control"
# 				})

# 		}

e_learning/course/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Video,Student,Author
from .forms import videoform,authorform,studentform,Submit_valid_proofs
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
User = get_user_model()


# Page for Guest User and whenever User opens on another tab depending upon the type of user , page should open
def visit(req):

	if req.user.is_anonymous:
		obj=Video.objects.all()
		return render(req,'visit.html',{'data':obj})
	elif req.user.is_superuser:
		return render(req,'admin_html_page.html')
	elif req.user.role=='Student':
		return redirect("s_home")
	else:
		return redirect("a_home")

# Sign Up Form For Student
def s_signup(req):
	if req.method=='POST':
		form=studentform(req.POST)
		print("I am in the POST form")
		if form.is_valid():
			print("Form is valid")
			r=form.save(commit=False)
			r.save()
			obj=Student.objects.create(user_id=int(r.uid()))
			obj.s_name=r.first_name + " "+r.last_name;
			obj.email=r.email
			obj.save()
			print("Student name is ",obj.s_name)
			username = req.POST['username']
			password1 = req.POST['password1']
			user = authenticate(req, username=username, password=password1)
			login(req,user)
			return redirect("s_home")

		else:
			print("Form is invalid")
			print(form.errors)
			return render(req,'reg_student.html',{'data':form})
			# print(form)
			# print("Invalid Form")
			# print(form.errors)
			# return render(request, 'app/add.html',{'form':form})

	form=studentform()
	return render(req,'reg_student.html',{'data':form})

# Sign Up Form For Teacher
def a_signup(req):

	if req.method=='POST':
		form=authorform(req.POST,req.FILES)
		if form.is_valid():
			r=form.save(commit=False)
			r.role="Teacher"
			r.save()
			obj=Author.objects.create(user_id=int(r.uid()))
			obj.a_name=r.first_name + " "+r.last_name;
			obj.email=r.email
			# obj.a_qualification=r.a_qualification
			obj.a_qualification=req.POST['a_qualification']
			obj.proof=req.FILES['proof']
			obj.save()
			print("Author qualification is ",obj.a_qualification)
			username = req.POST['username']
			password1 = req.POST['password1']
			user = authenticate(req, username=username, password=password1)
			login(req,user)
			return redirect("a_home")
		
		print("Form is invalid")
		print(form.errors)
		return render(req,'reg_student.html',{'data':form})
		# print("Form is invalid")
		# print(form.errors)
	else:
		form=authorform()
		return render(req,'reg_author.html',{'data':form})

# Login Page for both Student,Teacher and Admin

def login_view(req):

	if req.method=='POST':
		username = req.POST['username']
		password = req.POST['password']
		user = authenticate(req, username=username, password=password)
		if user is not None:
			login(req,user)
			print("User role is ",user.role)
			
			if user.is_superuser:
				print("Hi Admin")
				return redirect(admin_home)

			elif user.role == "Student":
				if 'next_url' in req.POST:
					return redirect(req.POST.get('next_url'))
				return redirect(s_home)
			else:
				if 'next_url' in req.POST:
					return redirect(req.POST.get('next_url'))
				return redirect(a_home)
		else:
			print("Please Sign Up")
			return redirect("visit")
	else:
		form=AuthenticationForm()
		return render(req,'login.html',{'form':form})

# Home Page For Admin

def admin_home(req):
	return render(req,'admin_html_page.html')




# Home Page for Teacher
def a_home(req):
	data=Author.objects.get(user_id=req.user.id)
	obj3=Video.objects.all().filter(author_id=req.user.id)
	return render(req,'a_home.html',{'data':data,'data1':obj3})


# Home Page for Student
# Footer is properly applied to Student Home 
def s_home(req):
	data=Student.objects.get(user_id=req.user.id)
	obj=Video.objects.all()


	# obj1=Author.objects.get(user=req.user.id)
	# print("The name of Author is ",obj1.a_name)
	# obj2=obj1.video_set.all()
	# print("The courses of that author is ")
	# # print(obj2)


	print("The name of student is ",data)
	return render(req,'s_home.html',{'data':data,'obj':obj})


# Enrolling the student for the course

def s_enroll(req,vid):


	# print("The id of video is ",vid," and the id of student is ",req.user.id)

	student=Student.objects.get(user_id=req.user.id)


	video=Video.objects.get(id=vid)


	video.enrolled_student.add(student)

	# print(video.enrolled_student.all())



	return render(req,'student_enrolled.html',{'data':video})






# Page for playing Course

@login_required
def play(req,id):
	obj=Video.objects.get(id=id)
	return render(req,'play.html',{'data':obj})


# Page for adding a new Course 

@login_required(login_url='/a_login')
def add(req):
	print("Username of author is ",req.user.username)
	if req.method == 'POST':
		form = videoform(req.POST,req.FILES)
		if form.is_valid():
			obj=form.save(commit=False)
			print(obj)
			obj.author_id=req.user.id
			obj.save()
			return redirect('a_home')
	else:
		form = videoform()

	return render(req, 'addvideo.html', {'obj': form})



def s_learning(req):

	student=Student.objects.get(user_id=req.user.id)
	# print(student)
	
	video = Video.objects.filter(enrolled_student__s_name=student)
	
	# print(video)

	return render(req,'s_learning.html',{'data':video})




# See the status of author in Admin Page

def admin_teacher_status(req):
	obj=Author.objects.filter(status="Pending")
	print(obj)
	return render(req,"admin_teacher_status.html",{'data':obj})

# See the status of course

def admin_course_status(req):
	obj=Video.objects.filter(status="Pending")
	return render(req,"admin_course_status.html",{'data':obj})





# Changing the status of Teacher

def accept_teacher_status(req,aid):
	obj=Author.objects.get(user_id=aid)
	obj.status="Verified"
	obj.save()
	return redirect(admin_teacher_status)


def reject_teacher_status(req,aid):
	obj=Author.objects.get(user_id=aid)
	obj.status="Rejected"
	obj.save()
	return redirect(admin_teacher_status)


# Changing the status of Teacher


def accept_course_status(req,vid):
	obj=Video.objects.get(id=vid)
	obj.status="Verified"
	obj.save()
	return redirect(admin_course_status)



def reject_course_status(req,vid):
	obj=Video.objects.get(id=vid)
	obj.status="Rejected"
	obj.save()
	return redirect(admin_course_status)



def submit_valid_proof(req,aid):
	if req.method=='POST':
		obj1=Author.objects.get(user_id=aid)
		form = Submit_valid_proofs(req.POST,req.FILES)
		if form.is_valid():
			f1=form.save(commit=False)
			print(f1)
			obj1.status="Pending"
			obj1.proof=req.FILES['proof']
			obj1.save()
			return redirect('a_home')
		
	obj=Submit_valid_proofs()
	return render(req,'submit_valid_proofs.html',{'data':obj})



def video_rejected(req,vid):
	obj=Video.objects.get(id=vid)
	if req.method == 'POST':
		form = videoform(req.POST,req.FILES)
		if form.is_valid():
			obj1=form.save(commit=False)
			print(obj1)
			obj.title=req.POST['title']
			obj.status="Pending"
			obj.video=req.FILES['video']
			obj.save()
			# obj.author_id=req.user.id
			# obj.save()
			return redirect('a_home')
		else:
			print("form has Errors")
			print(form.errors)
			return render(req,"change_video_content.html",{'obj1':form,'data':obj})
	
	form = videoform(instance=obj)
	print(obj)
	return render(req,'change_video_content.html',{'obj1':form,'data':obj})



def remove_video(req,vid):
	obj=Video.objects.get(id=vid)
	obj.delete()
	return redirect(a_home)

# def stuents_enrolled(req,cid):
# 	obj=Video.objects.get(id=cid)
	



# #View the list of courses of that particular author

# def a_course(req):
# 	obj1=Author.objects.get(user=req.user.id)
# 	print("The name of Author is ",obj1.a_name)
# 	obj2=obj1.video_set.all()
# 	print("The courses of that author is ")
# 	# print(obj2)
# 	obj3=Video.objects.all().filter(author_id=req.user.id)
# 	print(obj3)
# 	return render(req,'a_course.html',{'data':obj3})

e_learning/course/templates/a_course.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="text/css" href="{% static 'images/1.jpg' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style type="text/css">
  div
  {
  	max-height: auto
  }
  @media (min-width:  992px) {
    .container{
        max-width: 1100px;
    }
  img
  {
    height: 120px;
  }
  
  .card {
    transition: transform 0.2s ease;
    height: 300px;
  }
  .card:hover
  {
    transform: scale(1.1);
  }
  .enroll
  {
  	text-align: center;
  }
  .card-title
  {
     
     height:70px;
  }
  sub 
  	{
            vertical-align: sub;
            font-size: small;
    }

  </style>
</head>

<body>
<nav class="navbar navbar-expand-sm navbar-light bg-light" style="border-bottom: 2px solid grey">
  
    <a class="navbar-brand " href="{% url 'a_home' %}"><p><strong>  E-Learning<sub>For Instructors</sub>  </strong></p></a>
    
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
    </button>
    
    <ul class="navbar-nav ml-auto mr-2">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'add' %}"><strong> Create Course </strong></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="logout">Logout</a>
      </li>      
      {% endif %}
    </ul>
    


</nav>
<h3 class=" m-2 p-2"> My Courses </h3>

<div class="container">
<div class="row ">
	{% for i in data %}
	<div class="col-md-2 card mt-3 shadow-sm p-3 mb-5 bg-white rounded mx-3">
		
		<img src="{{i.banner.url}}"  class=" mt-1 " width="150px" >
		<div align="center" class="card-body">
      <div class="card-title">{{i.title}}</div>		
		  <button class="btn btn-success">View</button>
		</div>

    </div>
	{% endfor %}
</div>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

e_learning/course/templates/a_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="text/css" href="{% static 'images/1.jpg' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style type="text/css">
  sub 
  {
          vertical-align: sub;
          font-size: small;
  }
  div
  {
    max-height: auto
  }
  @media (min-width:  992px) {
    .container{
        max-width: 1100px;
    }
  img
  {
    height: 120px;
  }
  
  .card {
    transition: transform 0.2s ease;
    height: auto;
  }
  .card:hover
  {
    transform: scale(1.1);
  }
  .enroll
  {
    text-align: center;
  }
  .card-title
  {
     
     height:70px;
  }
  .footer 
  {
    color: #707070;
    height: 60px;
    width:100%;
    font-size: small;
    text-align: center;
  }
  html,body
  {
    height: 100%;
  }
  .content-division
  {
    min-height: 100%;
  }
  .content-main
  {
    overflow: auto;
    padding-bottom: 100px;
  }
  .course-image
  {
    height: 120px;
    border:1px dotted red;
    position: relative;
    z-index: -10;
  }
  .admin-permission
  {
    position: absolute;
    top:50px;
    left:20px;
    /*border: 3px solid #73AD21;*/
  }
  </style>


</head>
<body>
<div class="content-division">
  <nav class="navbar navbar-expand-sm navbar-light bg-light" style="border-bottom: 2px solid grey">
    
      <a class="navbar-brand " href="{% url 'a_home' %}"><span><strong>  E-Learning<sub>For Instructors</sub>  </strong></span></a>
      
      
      
      
      <ul class="navbar-nav ml-auto mr-2">
        {% if data.status == "Verified" %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'add' %}"><strong> Create Course </strong></a>
          </li>

        {% elif data.status == 'Rejected' %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'submit_valid_proof' data.user_id %}"><strong> Submit Valid Proofs </strong></a>
          </li>

        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="logout">Logout</a>
        </li>      
      </ul>
  </nav>



  <div class="container-fluid content-main">
    {% if data.status == "Pending" %}

      <h3 class="mt-4 ml-2" style="line-height:1.5;"> Welcome {{data.a_name.title}}, Your Account is being verified by Admin </h3>


    {% elif data.status == "Rejected" %}


      <h3 class="mt-4 ml-2" style="line-height:1.5;"> Welcome {{data.a_name.title}}, Your Account verification failed. Kindly Submit Valid  Proofs </h3>      

    {% else %}

    <h3 class="mt-4 ml-2"> Welcome {{data.a_name.title}}. Your Account has been verified. </h3>

    <div class="container mt-4">
      <div class="row ">
        {% for i in data1 %}
          {% if i.status == "Verified" %}
            <div class="col-md-2 card mt-3 shadow-sm p-3 mb-5 bg-white rounded mx-3">
              <a href="{% url 'play' i.id %}" style="text-decoration: none;color:inherit;">
                <img src="{{i.banner.url}}"  class=" mt-1 " width="150px" >
                <div align="center" class="card-body">
                  <div class="card-title">{{i.title}}</div>   
                  <button class="btn btn-success">View</button>
                </div>
              </a>

            </div>
            
            {% elif i.status == "Rejected" %}

            <div class="col-md-2 card mt-3 shadow-sm p-3 mb-5 bg-white rounded mx-3">
              <a href="{% url 'video_rejected' i.id %}" style="text-decoration: none;color:inherit;">
                <img src="{{i.banner.url}}"  class=" mt-1 course-image" width="150px" >
                <span class="admin-permission" style="text-align: center;padding-right: 15px"><h6>Admin Rejected the Video</h6></span>

                <div align="center" class="card-body">
                  <div class="card-title">{{i.title}}</div>   
                  <span class="btn btn-success">Change</span>
                </div>

              </a>  
            </div>

            {% else %}
            
            <div class="col-md-2 card mt-3 shadow-sm p-3 mb-5 bg-white rounded mx-3">
              <a href="{% url 'play' i.id %}" style="text-decoration: none;color:inherit;">
                <img src="{{i.banner.url}}"  class=" mt-1 course-image" width="150px" >
                <span class="admin-permission" style="text-align: center;padding-right: 15px"><h6>Admin Permission Pending</h6></span>

                <div align="center" class="card-body">
                  <div class="card-title">{{i.title}}</div>   
                  <button class="btn btn-success">View</button>
                </div>

              </a>  
            </div>  
          {% endif %}
        {% endfor %}
      
      </div>
    </div>

    {% endif %}
  </div>

</div>
<div class="footer mt-4 mb-1 bg-secondary text-light " style=" width: 100%; height: 60px;text-align: center;">
  <p>Footer</p>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

e_learning/course/templates/addvideo.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Course</title>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body align="center" style="margin-top: 20px;" >
	<h2 align="center"> Add Course </h2>
	<div class="col-md-6 offset-3 mt-5 card shadow-lg h-90" >
	<div class="card-body "> 
	<form method="post" enctype="multipart/form-data">
	    {% csrf_token %}
	    
		{% for i in obj %}


		{% if forloop.counter == 1 %}

			{{i}}
			<div class="mt-2 ml-3">**{{i.field.help_text}}</div><br>

		{% elif forloop.counter == 2 %}

			<label for="id_video" >Upload the course banner</label><br>
			{{i}}<br><BR>

		{% elif forloop.counter == 3 %}

			<label for="id_video" >Upload the course video</label><br>
			{{i}}<br>			

		{% else %}

			{{i}}

		{% endif %}			
		
		
	

		{% endfor %}

		<div class="row mt-2" >
		<a href="{% url 'a_home' %}" class="mx-auto col-md-4 form-control btn btn-outline-primary">Return to Home</a>
	    <input type="submit" class="col-md-4 mx-auto form-control btn btn-outline-success" value="Upload">
		</div>
	</form>
	</div>
	</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

e_learning/course/templates/logout.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Course</title>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style type="text/css">
  	table
  	{
  		border-collapse: separate;
  		border-spacing: 10px 10px;
  	}
  </style>
</head>
<body align="center" style="margin-top: 20px;" >

<div class="container">
  <div class="jumbotron mt-4">
	<h3>Thanks for spending some quality time with the E-learning today.</h3>
	<br><br>
	<div class="row">
	<a href="{% url 'login' %}" class="mx-auto col-md-4 form-control btn btn-outline-success ">Log in Again</a>
	<a href="{% url 'visit' %}" class="col-md-4 mx-auto form-control btn btn-outline-primary">Return to Home</a>
  	</div>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>